### ISSUE TITLE
Usage request

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-floodsub#59]
So I'd like to use this library to create a p2p pubsub capability, embedded in an app I'm writing.  ATM, the price of addmission is I have to figure out how to

- Create a capable floodsub instance (via underlying *Host)
- connect this instance to others who are interested in subscribing (via underlying *Host)
- handling various people joining, leaving, becoming stale
- propagating messages to those I know who are interested
- making sure the actual messages get to where they should :)

ATM I ***love*** the modularity that libp2p provides compared to `*ipfs.IpfsNode`, but I'd like to learn how to use it.  I'd like an example that shows how to create a `*floodsub.PubSub` instance that can publish some `[]bytes` and interested nodes could join, leave, etc.

My issue here is that `floodsub` seems to require a ton of other imports to use, and I cant imbed a `*floodsub.PubSub` without also embedding a host, and a PeerStore and maybe a `[]*floodsub.Subscription`.   Doing all this is doubtless, no problem - of only I knew what to do, or had some examples...

**Comment by jvsteiner** [comment]
complicating usage is that the test code uses unexported fields to receive messages and that go-walker revels only one package that imports this one, and the usage there is not very helpful in the context of standalone use.

**Comment by Stebalien** [comment]
You will a libp2p host but that should be it. You can find a good example of how to create one [here](https://github.com/libp2p/go-libp2p/blob/master/examples/echo/main.go). For actually *using* this package, we could definitely use some examples... For now, I recommend taking a look at the [basic test case](https://github.com/libp2p/go-floodsub/blob/c82e67dcd38f69dee40567df11bf595b82f1dfe5/floodsub_test.go#L108-L148) (ignoring the parts concerned with setting up and connecting the hosts).

The compact tutorial is:

1. You can subscribe to (join) a topic by calling `.Subscribe("topic")` on the pubsub instance (returns a subscription object).
2. You can receive messages from the topic by calling `.Next(ctx)` on the subscription object.
3. You can publish messages on a topic by calling `.Publish("topic", someData)` on the pubsub instance.
4. You can unsubscribe by calling `.Cancel()` on the subscription object.

The tricky part will be finding/connecting to peers interested in the subject. However, you can actually use pubsub for that if you want (have all peers subscribe to/publish interest on an "interested in" channel).

**Comment by jvsteiner** [comment]
Trying to follow along, but so far have been unable to successfully pass a message using go-floodsub.  I have the following code, much of which is draw from the example of how to create a host.  (In fact, I had already created one, but when using it, I encountered the same error, which I detail below)

```
package narc

import (
	"context"
	"crypto/rand"
	"fmt"
	"io"
	"log"
	mrand "math/rand"

	libp2p "gx/ipfs/QmPd5qhppUqewTQMfStvNNCFtcxiWGsnE6Vs3va6788gsX/go-libp2p"
	floodsub "gx/ipfs/QmSjoxpBJV71bpSojnUY1K382Ly3Up55EspnDx6EKAmQX4/go-libp2p-floodsub"
	crypto "gx/ipfs/QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo/go-libp2p-crypto"
	pstore "gx/ipfs/QmeZVQzUrXqaszo24DAoHfGzcmCptN9JyngLkGAiEfk2x7/go-libp2p-peerstore"
	host "gx/ipfs/QmfCtHMCd9xFvehvHeVxtKVXJTMVTuHhyPRVHEXetn87vL/go-libp2p-host"

	ma "gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr"
)

type Narc struct {
	ps   *floodsub.PubSub
	host host.Host
	subs []*floodsub.Subscription
}

func New(listenPort int, secio bool, seed int64) (*Narc, error) {
	ctx := context.Background()
	h, err := makeBasicHost(listenPort, secio, seed)
	if err != nil {
		return nil, err
	}
	ps, err := floodsub.NewFloodSub(ctx, h)
	if err != nil {
		return nil, err
	}
	return &Narc{ps: ps, host: h}, nil
}

func (n *Narc) Connect(pi pstore.PeerInfo) error {
	n.host.Peerstore().AddAddrs(pi.ID, pi.Addrs, pstore.PermanentAddrTTL)
	err := n.host.Connect(context.Background(), pi)
	if err != nil {
		return err
	}
	return nil
}

func (n *Narc) Self() pstore.PeerInfo {
	pi := n.host.Peerstore().PeerInfo(n.host.ID())
	pi.Addrs = n.host.Addrs()
	return pi
}

func (n *Narc) Subscribe(topic string) error {
	sub, err := n.ps.Subscribe(topic)
	if err != nil {
		return err
	}
	n.subs = append(n.subs, sub)
	return nil
}

// makeBasicHost creates a LibP2P host with a random peer ID listening on the
// given multiaddress. It will use secio if secio is true.
func makeBasicHost(listenPort int, secio bool, randseed int64) (host.Host, error) {

	// If the seed is zero, use real cryptographic randomness. Otherwise, use a
	// deterministic randomness source to make generated keys stay the same
	// across multiple runs
	var r io.Reader
	if randseed == 0 {
		r = rand.Reader
	} else {
		r = mrand.New(mrand.NewSource(randseed))
	}

	// Generate a key pair for this host. We will use it at least
	// to obtain a valid host ID.
	priv, _, err := crypto.GenerateKeyPairWithReader(crypto.RSA, 2048, r)
	if err != nil {
		return nil, err
	}

	opts := []libp2p.Option{
		libp2p.ListenAddrStrings(fmt.Sprintf("/ip4/127.0.0.1/tcp/%d", listenPort)),
		libp2p.Identity(priv),
	}

	if !secio {
		opts = append(opts, libp2p.NoEncryption())
	}

	basicHost, err := libp2p.New(context.Background(), opts...)
	if err != nil {
		return nil, err
	}

	// Build host multiaddress
	hostAddr, _ := ma.NewMultiaddr(fmt.Sprintf("/ipfs/%s", basicHost.ID().Pretty()))

	// Now we can build a full multiaddress to reach this host
	// by encapsulating both addresses:
	addr := basicHost.Addrs()[0]
	fullAddr := addr.Encapsulate(hostAddr)
	log.Printf("I am %s\n", fullAddr)
	if secio {
		log.Printf("Now run \"./echo -l %d -d %s -secio\" on a different terminal\n", listenPort+1, fullAddr)
	} else {
		log.Printf("Now run \"./echo -l %d -d %s\" on a different terminal\n", listenPort+1, fullAddr)
	}

	return basicHost, nil
}
```
The problems start when I call `Connect()` - I am getting:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x137cb2a]

goroutine 56 [running]:
gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream.(*Swarm).NewStreamWithConn(0xc4200a0180, 0xc4205b8080, 0x1, 0x1, 0x1636601)
	/Users/jamie/Code/go/src/gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream/swarm.go:328 +0xba
gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream.(*Swarm).newStreamSelectConn(0xc4200a0180, 0x1635660, 0xc42015c018, 0x1, 0x1, 0x1, 0x11c938a, 0xc420077740)
	/Users/jamie/Code/go/src/gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream/swarm.go:284 +0xd6
gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream.(*Swarm).NewStreamWithGroup(0xc4200a0180, 0x14999c0, 0xc4205accd8, 0x1, 0xc4205acce8, 0x11c941e)
	/Users/jamie/Code/go/src/gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream/swarm.go:306 +0x9b
gx/ipfs/QmSKrS9EF4V8FpD1d5FUGQiwYLNkXcxKabWgT2aWNVnQie/go-libp2p-swarm.(*Swarm).NewStreamWithPeer(0xc4200ae200, 0x187a8e0, 0xc42001c0d8, 0x0, 0x0, 0x2, 0x1, 0x0)
	/Users/jamie/Code/go/src/gx/ipfs/QmSKrS9EF4V8FpD1d5FUGQiwYLNkXcxKabWgT2aWNVnQie/go-libp2p-swarm/swarm.go:285 +0x104
gx/ipfs/QmSKrS9EF4V8FpD1d5FUGQiwYLNkXcxKabWgT2aWNVnQie/go-libp2p-swarm.(*Network).NewStream(0xc4200ae200, 0x187a8e0, 0xc42001c0d8, 0x0, 0x0, 0xc4205c4140, 0x0, 0x1, 0x0)
	/Users/jamie/Code/go/src/gx/ipfs/QmSKrS9EF4V8FpD1d5FUGQiwYLNkXcxKabWgT2aWNVnQie/go-libp2p-swarm/swarm_net.go:142 +0x160
gx/ipfs/QmPd5qhppUqewTQMfStvNNCFtcxiWGsnE6Vs3va6788gsX/go-libp2p/p2p/host/basic.(*BasicHost).NewStream(0xc42043c200, 0x187a8e0, 0xc42001c0d8, 0x0, 0x0, 0xc4205c4120, 0x1, 0x1, 0x9d50e8c181e325fd, 0xb3d2742ee65775dc, ...)
	/Users/jamie/Code/go/src/gx/ipfs/QmPd5qhppUqewTQMfStvNNCFtcxiWGsnE6Vs3va6788gsX/go-libp2p/p2p/host/basic/basic_host.go:355 +0x23a
gx/ipfs/QmSjoxpBJV71bpSojnUY1K382Ly3Up55EspnDx6EKAmQX4/go-libp2p-floodsub.(*PubSubNotif).Connected.func1(0xc42008c840, 0x187d640, 0xc4205b8080)
	/Users/jamie/Code/go/src/gx/ipfs/QmSjoxpBJV71bpSojnUY1K382Ly3Up55EspnDx6EKAmQX4/go-libp2p-floodsub/notify.go:20 +0xfc
created by gx/ipfs/QmSjoxpBJV71bpSojnUY1K382Ly3Up55EspnDx6EKAmQX4/go-libp2p-floodsub.(*PubSubNotif).Connected
	/Users/jamie/Code/go/src/gx/ipfs/QmSjoxpBJV71bpSojnUY1K382Ly3Up55EspnDx6EKAmQX4/go-libp2p-floodsub/notify.go:19 +0x53
exit status 2
```
I've followed the stack trace through all the listed packages, and as far as I can tell, it has something to do with being unable to open a new Stream, but I cant wrap my head around what I'm doing wrong.  I'm guessing it might be something to do with the way I am storing or using addresses, but I can't work it out.  I noticed that the error originates in the cast-as `(*PubSubNotif)` area of the code, which looks like it's still under a bit of development.  Any help or pointers that you have time to throw my way would be much appreciated!

Thanks!

**Comment by Stebalien** [comment]
Ah. You're missing a stream multiplexer and we were missing a check to make sure you *had* one. Try upgrading to the latest go-libp2p, I just merged a PR that should make this work out of the box (it specifies a default stream muxer).

**Comment by Stebalien** [comment]
Note: the *old* way to do this would have been to pass a `Muxer(DefaultMuxer())` option to the libp2p constructor.

**Comment by jvsteiner** [comment]
nice one - will give it a try and report back.  I figured it might be something obvious to everyone but me. :)  Many thanks for the quick reply!

**Comment by jvsteiner** [comment]
Hi - got the basics working, many thanks.  Couple of notes from the experience.  I didn't use `secio` and got a complaint from the Peerstore: 
```ERROR net/identi: did not have own public key in Peerstore id.go:182```
I added the key manually, that made the error go away, but it worked without it - maybe should be a Warning instead.
Finally, I needed to add a little `time.Sleep` just after the calls to `Subscribe()` which hung me up a little, since `Subscribe()` was returning the subscription and a nil error right away.  Without the sleep, the call to `subscription.Next()` blocked forever.  Could this be a deadlock issue?

**Comment by Stebalien** [comment]
@jvsteiner under normal operating conditions, not having one's own peer ID *is* an error. We could add a check to the identify service but I'd rather leave the insecure case as annoying and noisy as possible :wink:.

Usually we deal with that by doing regular releases. If you ever need a bugfix, ask (naming the specific packages you need) and we'll probably be able to cut a release for you (unless something else is blocking the release).

**Comment by jvsteiner** [comment]
I decided to reopen this issue, since there is some useful context, rather than make a new one - hope that's ok.

above: "The tricky part will be finding/connecting to peers interested in the subject. However, you can actually use pubsub for that if you want (have all peers subscribe to/publish interest on an "interested in" channel)."

I tried to do this by writing some subscription handlers that are able to make a connection to other topically interested peers.  In a basic sense, this is needed, I learned, because peers that are not subscribed to a topic, do not propagate messages for that topic.  This is by design, and is understandable.

In my tests, I create a slice of pubsubs, where each is connected only to immediate neighbors.  All subscribe to a pair of discovery req/resp topics.  I then use the discovery process to directly connect the first and last members who share interest in a special topic that the others are not interested in.  Discovery works, and new connections are made, although i get `ERROR   floodsub: already have connection to peer: <peer.ID dJjnY6> floodsub.go:162`. (not a self connection issue)

I started out pre-subscribing the first and last to the special topic, but it didn't work.  Then, reading through the code, it seemed that peers indicate their interest in a topic, at the point of Subscribing - ie. once a peer has subscribed, if it subsequently connects to a new peer who is also subscribed to that topic, neither will _know_ that the other is interested, because all the announcing has already happened.  More specifically it seems `peer.ListPeers(topic)` would not indicate the new peer, even though they are indeed directly connected.  However other of my tests seem to indicate that subscribing before connecting does not make a difference.

I nevertheless tried subscribing _after_ discovery/direct connection, but it made no difference: `ListPeers` still didn't show interest in the special topic for the intended peers.  Inspection shows that all peers show interest in the discovery topics.

Any ideas?
